### ISSUE TITLE
Compute local odometry

### ISSUE THREAD

**Issue by erickmu1** [UTRA-ART/Caffeine#8]
**Description:**
- Use simulated sensors as inputs and compute an odometry measurement from them
- This odometry value should be reported with respect to the odom frame

**Goals:**
- [ ] Publish `odom` frame
- [ ] Connect simulated sensors to `robot_localization`

**Acceptance Criteria:**
- [ ] `odom` frame exists
- [ ] When using teleop, odometry value is reasonably accurate with acceptable drift

**Notes:**
- use the `ekf_localization_node` from `robot_localization`
- we can use IMU, Visual Odom, and Wheel Odom to fuse and compute local odometry
- GPS cannot be used to provide local odometry

**Comment by erickmu1** [comment]
There is warning that appears whenever `robot_localization`'s `ekf_localization` node is run:
```
process[ekf_localization-1]: started with pid [17126]
[ WARN] [1594599261.800555901, 687.785000000]: Failed to meet update rate! Took 687.78499999999996817
[ WARN] [1594599261.801476426, 687.785000000]: Failed to meet update rate! Took 487.78500000000002501
```

By looking through the published `/diagnostics` topic, I concluded that these **warnings are benign** and there is nothing we can do about it without modifying the source code. Here are two messages from the `/diagnostics` topic that support my conclusion:
```
header: 
  seq: 11
  stamp: 
    secs: 686
    nsecs:   8000000
  frame_id: ''
status: 
  - 
    level: 0
    name: "ekf_localization: Filter diagnostic updater"
    message: "The robot_localization state estimation node appears to be functioning properly."
    hardware_id: "none"
    values: []
  - 
    level: 1
    name: "ekf_localization: odometry/filtered topic status"
    message: "Frequency too low."
    hardware_id: "none"
    values: 
      - 
        key: "Events in window"
        value: "450"
      - 
        key: "Events since startup"
        value: "450"
      - 
        key: "Duration of window (s)"
        value: "686.008000"
      - 
        key: "Actual frequency (Hz)"
        value: "0.655969"
      - 
        key: "Minimum acceptable frequency (Hz)"
        value: "43.200000"
      - 
        key: "Maximum acceptable frequency (Hz)"
        value: "57.200000"
---
header: 
  seq: 12
  stamp: 
    secs: 687
    nsecs:   8000000
  frame_id: ''
status: 
  - 
    level: 0
    name: "ekf_localization: Filter diagnostic updater"
    message: "The robot_localization state estimation node appears to be functioning properly."
    hardware_id: "none"
    values: []
  - 
    level: 0
    name: "ekf_localization: odometry/filtered topic status"
    message: ''
    hardware_id: "none"
    values: 
      - 
        key: "Events in window"
        value: "500"
      - 
        key: "Events since startup"
        value: "500"
      - 
        key: "Duration of window (s)"
        value: "10.000000"
      - 
        key: "Actual frequency (Hz)"
        value: "50.000000"
      - 
        key: "Minimum acceptable frequency (Hz)"
        value: "43.200000"
      - 
        key: "Maximum acceptable frequency (Hz)"
        value: "57.200000"
```

From the above excerpt, I concluded that there is some *start up time* for the `/odometry/filtered` topic to be published at the desired frequency (**Note:** the used config file specifies `frequency: 50.0`). This is because the `'Frequency too low'` message is no longer published after a certain time (ie. the start up time). Likewise, I managed to remove the warnings by using `frequency: 0.0005`, which is a publish rate smaller than the smallest publish rate attained by `ekf_localization` during its start up period.

**Altogether**, feel free to ignore this warning and continue adding sensors to `ekf_localization`.
